---
name: Comment Jira
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  comment-jira-build:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
            node-version-file: comment-jira/package.json
      - name: install dependencies
        working-directory: ./comment-jira
        run: |
          npm ci
      - name: build
        working-directory: ./comment-jira
        run: |
          npm run build
      - name: Check for uncommitted files
        run: |
          export FILES=
          FILES=$(git ls-files -o -m --directory --exclude-standard --no-empty-directory)
          export LINES=
          LINES=$(echo "$FILES" | awk 'NF' | wc -l)
          if [ "$LINES" -ne 0 ]; then
            echo "Detected files that need to be committed:"
            echo "${FILES//^/ }"
            echo ""
            echo "Try running: make gen-docs"
            exit 1
          fi
  comment-jira-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
            node-version-file: comment-jira/package.json
      - name: install dependencies
        working-directory: ./comment-jira
        run: |
          npm ci
      - name: Run tests
        working-directory: ./comment-jira
        run: |
          npm run test
  comment-jira-test:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Write inline Nginx config
        run: |
          cat <<EOF > nginx.conf
          events {}

          http {
              server {
                  listen 80;

                  location /rest/api/2/issue/TEST-123/comment {
                      default_type application/json;
                      return 201 '{"id": "10000"}';
                  }

                  location /ping {
                      default_type plain/text;
                      return 200 'PONG';
                  }
              }
          }
          EOF

      - name: Start Nginx with Docker
        run: |
          docker run -d --name mock-nginx \
            -v ${{ github.workspace }}/nginx.conf:/etc/nginx/nginx.conf:ro \
            -p 55000:80 nginx:alpine

      - name: Wait for Nginx to be ready (via /ping)
        run: |
          for i in {1..50}; do
            if curl -s http://localhost:55000/ping > /dev/null; then
              echo "âœ… Nginx is ready!"
              exit 0
            fi
            echo "Waiting for Nginx..."
            docker logs mock-nginx
            sleep 1
          done
          echo "Nginx is not reacheable"
          exit 1

      - uses: ./comment-jira/
        with:
          token: test
          issue-key: TEST-123
          comment: |
            Test comment from GitHub Actions
            with multiple lines
          api-base: http://localhost:55000 